project:
  type: website
  output-dir: docs

website:
  title: "bytesizedchem"
  site-url: https://bytesizedchem.com
  description: "A Digital Chemistry Atlas"
  # favicon: assets/favicon.png
  navbar:
    right:
      - about.qmd
      - text: "Subscribe"
        href: https://bytesizedchem.substack.com/subscribe
      - icon: github
        href: https://github.com/mlederbauer
      - icon: twitter
        href: https://twitter.com/maglederb
      - icon: linkedin
        href: https://www.linkedin.com/in/magdalena-lederbauer/
    logo: assets/favicon.png
  # margin-header: subscribe.html
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto